import { MODULE_AGENT_OPERATION_API_OPERATIONS } from "@/lib/contracts/module-agent-command-catalog.contract"

export type AgentOperationApiStatus =
  | "contract_only_until_auth_proof"
  | "protected_dry_run_ready"

export type AgentOperationApiMethod = "POST"

export type AgentOperationApiMode = "dry_run"

export type AgentOperationApiRisk = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"

export type AgentOperationApiApproval =
  | "AUTO_READ"
  | "AUTO_PROPOSE"
  | "HUMAN_APPROVAL_REQUIRED"
  | "BLOCKED"

export type AgentOperationApiOperation = {
  id: string
  ownerAgent: string
  targetModule: string
  riskLevel: AgentOperationApiRisk
  approvalLevel: AgentOperationApiApproval
  allowedModes: readonly AgentOperationApiMode[]
  scopes: readonly string[]
  cliParityCommand: string
  blockedActions: readonly string[]
}

export type AgentOperationApiRequestField = {
  key: string
  required: boolean
  valueType: "string" | "string_array" | "object" | "literal"
  allowedValues?: readonly string[]
  rule: string
}

export type AgentOperationApiResponse = {
  statusCode: 200 | 400 | 401 | 403 | 405 | 503
  label: string
  bodyShape: readonly string[]
  cache: "private_no_store"
}

export type AgentOperationApiContract = {
  id: "AGENT-009"
  version: "0.1.0"
  status: AgentOperationApiStatus
  endpoint: {
    method: AgentOperationApiMethod
    path: "/api/agent-operations/dry-run"
    routeHandlerImplemented: boolean
    routeHandlerBlockedBy: readonly string[]
    runtimeRequirement: string
  }
  request: {
    contentType: "application/json"
    bodyFields: readonly AgentOperationApiRequestField[]
    forbiddenInputFields: readonly string[]
  }
  responses: readonly AgentOperationApiResponse[]
  operations: readonly AgentOperationApiOperation[]
  bffFlow: readonly string[]
  safety: {
    protectedOwnerOnly: true
    publicEndpointCreated: false
    internalHttpEndpointCreated: boolean
    externalRegistryWrite: false
    databaseWrite: false
    providerCall: false
    readsPrivateRecords: false
    externalAgentDatabaseAccess: false
    autonomousExecution: false
    highRiskFinalWrite: false
    appendAuditNow: false
  }
  futureAudit: {
    eventFamily: "agent.operation"
    persistence: "future_append_only"
    prerequisite: "AUDIT-OPS-001 runtime storage and protected route auth proof"
  }
  sourceRefs: readonly string[]
  rejectedAlternatives: readonly string[]
}

export const AGENT_OPERATION_API_OPERATIONS =
  MODULE_AGENT_OPERATION_API_OPERATIONS satisfies readonly AgentOperationApiOperation[]

export const AGENT_OPERATION_API_CONTRACT = {
  id: "AGENT-009",
  version: "0.1.0",
  status: "protected_dry_run_ready",
  endpoint: {
    method: "POST",
    path: "/api/agent-operations/dry-run",
    routeHandlerImplemented: true,
    routeHandlerBlockedBy: [
      "External/public endpoint exposure remains blocked.",
      "Only internal protected owner mock-mode or proven owner session dry-run is allowed.",
    ],
    runtimeRequirement:
      "When enabled, the route must run requireUser(), owner-only authorization, request validation, registry lookup, dry-run proof mapping, and no-store response handling before any output.",
  },
  request: {
    contentType: "application/json",
    bodyFields: [
      {
        key: "operationId",
        required: true,
        valueType: "string",
        rule: "Must match one operation id from AGENT_OPERATION_API_OPERATIONS.",
      },
      {
        key: "mode",
        required: true,
        valueType: "literal",
        allowedValues: ["dry_run"],
        rule: "Only dry_run is accepted in AGENT-009.",
      },
      {
        key: "agentLabel",
        required: false,
        valueType: "string",
        rule: "Optional override must match the operation owner agent and an internal AgentFacts-lite manifest.",
      },
      {
        key: "targetModule",
        required: false,
        valueType: "string",
        rule: "Optional override must match the operation target module.",
      },
      {
        key: "requestedChecks",
        required: false,
        valueType: "string_array",
        rule: "Optional labels only; must not include private records or secret values.",
      },
      {
        key: "clientRequestId",
        required: false,
        valueType: "string",
        rule: "Optional idempotency/debug marker generated by the UI; not a database id.",
      },
    ],
    forbiddenInputFields: [
      "cookies",
      "session values",
      "raw auth claims",
      "provider payloads",
      "database URLs",
      "database hosts",
      "profile ids",
      "private record bodies",
      "access tokens",
      "refresh tokens",
      "service-role keys",
    ],
  },
  responses: [
    {
      statusCode: 200,
      label: "ready_for_owner_dry_run",
      bodyShape: [
        "schemaVersion",
        "generatedAt",
        "mode",
        "status",
        "selectedOperation",
        "agentManifestSnapshot",
        "registrySnapshot",
        "safety",
        "validation",
        "nextReview",
      ],
      cache: "private_no_store",
    },
    {
      statusCode: 400,
      label: "invalid_operation_or_input",
      bodyShape: ["error", "code", "allowedOperations", "nextAction"],
      cache: "private_no_store",
    },
    {
      statusCode: 401,
      label: "unauthenticated",
      bodyShape: ["error", "code", "nextAction"],
      cache: "private_no_store",
    },
    {
      statusCode: 403,
      label: "not_owner_or_admin",
      bodyShape: ["error", "code", "nextAction"],
      cache: "private_no_store",
    },
    {
      statusCode: 405,
      label: "method_not_allowed",
      bodyShape: ["error", "code", "allowedMethods"],
      cache: "private_no_store",
    },
    {
      statusCode: 503,
      label: "registry_unavailable",
      bodyShape: ["error", "code", "nextAction"],
      cache: "private_no_store",
    },
  ],
  operations: AGENT_OPERATION_API_OPERATIONS,
  bffFlow: [
    "POST /api/agent-operations/dry-run",
    "requireUser()",
    "assert owner-only authorization",
    "validate JSON body and reject non-dry_run modes",
    "load generated internal AgentFacts-lite registry files",
    "match operation id, owner agent, target module, scopes, approval level, and blocked actions",
    "return AgentOperationDryRunProof DTO with Cache-Control private, no-store",
    "append OperatingAuditEvent later after runtime audit storage exists",
  ],
  safety: {
    protectedOwnerOnly: true,
    publicEndpointCreated: false,
    internalHttpEndpointCreated: true,
    externalRegistryWrite: false,
    databaseWrite: false,
    providerCall: false,
    readsPrivateRecords: false,
    externalAgentDatabaseAccess: false,
    autonomousExecution: false,
    highRiskFinalWrite: false,
    appendAuditNow: false,
  },
  futureAudit: {
    eventFamily: "agent.operation",
    persistence: "future_append_only",
    prerequisite: "AUDIT-OPS-001 runtime storage and protected route auth proof",
  },
  sourceRefs: [
    "docs/02_architecture-and-rules/ARC-028_nanda-agent-protocol-alignment.md",
    "docs/02_architecture-and-rules/ARC-029_agent-operation-dry-run-contract.md",
    "docs/07_research-and-design/RES-004_agent-collaboration-nanda-gap-research.md",
    "docs/08_acceptance-and-qa/ACC-002_module-acceptance-criteria.md",
    "scripts/agent-operation-dry-run.mjs",
    "src/lib/contracts/module-agent-command-catalog.contract.ts",
  ],
  rejectedAlternatives: [
    "Expose the route as a public or external agent endpoint.",
    "Allow non-owner roles to call dry-run operations.",
    "Expose a public agent operation endpoint.",
    "Accept execute or run modes.",
    "Read database rows or provider payloads in the dry-run API.",
    "Append runtime audit events before protected route auth proof and audit storage exist.",
  ],
} as const satisfies AgentOperationApiContract

export const AGENT_OPERATION_API_CONTRACT_SUMMARY = {
  taskId: "AGENT-009",
  status: AGENT_OPERATION_API_CONTRACT.status,
  routeHandlerImplemented: AGENT_OPERATION_API_CONTRACT.endpoint.routeHandlerImplemented,
  operationCount: AGENT_OPERATION_API_CONTRACT.operations.length,
  allowedMode: "dry_run",
  externalRegisterable: false,
  nextTask:
    "Use the protected dry-run route from the owner command UI, then decide whether AUTH-005 or WORK-009 can run from owner-provided evidence.",
} as const
