export type OperatingAuditModuleKey =
  | "work"
  | "research"
  | "ai-input"
  | "workflow"
  | "life"
  | "finance"
  | "chamber"
  | "company"
  | "client-portal"
  | "agent-team-os"
  | "auth"
  | "admin"
  | "settings"
  | "deployment"

export type OperatingAuditActorType =
  | "owner"
  | "system"
  | "internal_agent"
  | "public_token"
  | "external_service"
  | "unknown"

export type OperatingAuditResult =
  | "success"
  | "failure"
  | "blocked"
  | "dry_run"
  | "proposal_created"
  | "approved"
  | "rejected"
  | "rolled_back"

export type OperatingAuditRisk = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"

export type OperatingAuditApprovalLevel =
  | "none"
  | "owner_review"
  | "admin_review"
  | "human_required"
  | "external_approval_required"

export type OperatingAuditRetentionClass =
  | "standard_180_days"
  | "security_1_year"
  | "high_risk_7_year_review_required"

export type OperatingAuditSourceKind =
  | "server_action"
  | "route_handler"
  | "server_component_loader"
  | "cli_proof"
  | "agent_dry_run"
  | "manual_review"
  | "external_provider_event"

export type OperatingAuditFieldClass =
  | "identity"
  | "action"
  | "target"
  | "result"
  | "risk"
  | "source"
  | "agent"
  | "approval"
  | "provenance"
  | "redaction"
  | "retention"
  | "integrity"

export type OperatingAuditEventField = {
  name: string
  fieldClass: OperatingAuditFieldClass
  required: boolean
  piiPolicy: "opaque_ref" | "hash_only" | "safe_label" | "enum" | "json_redacted" | "nullable"
  notes: string
}

export type OperatingAuditEventFamily = {
  id: "AUDIT-OPS-001"
  familyKey: string
  moduleKeys: readonly OperatingAuditModuleKey[]
  actions: readonly string[]
  actorTypes: readonly OperatingAuditActorType[]
  targetTypes: readonly string[]
  defaultRisk: OperatingAuditRisk
  defaultApprovalLevel: OperatingAuditApprovalLevel
  retentionClass: OperatingAuditRetentionClass
  exampleSourceKind: OperatingAuditSourceKind
  sourceRefs: readonly string[]
  nextTask: string
  stopCondition: string
  schemaWriteAllowed: false
  runtimeWriteAllowed: false
}

const STATIC_AUDIT_GUARDS = {
  id: "AUDIT-OPS-001",
  schemaWriteAllowed: false,
  runtimeWriteAllowed: false,
} as const

export const OPERATING_AUDIT_EVENT_FIELDS = [
  {
    name: "id",
    fieldClass: "identity",
    required: true,
    piiPolicy: "opaque_ref",
    notes: "Stable audit event id generated by the future persistence layer.",
  },
  {
    name: "occurredAt",
    fieldClass: "provenance",
    required: true,
    piiPolicy: "safe_label",
    notes: "UTC action time supplied by the trusted server-side boundary when available.",
  },
  {
    name: "receivedAt",
    fieldClass: "provenance",
    required: true,
    piiPolicy: "safe_label",
    notes: "UTC ingestion time recorded by the audit writer.",
  },
  {
    name: "actorType",
    fieldClass: "identity",
    required: true,
    piiPolicy: "enum",
    notes: "Owner, system, internal agent, public token, external service, or unknown.",
  },
  {
    name: "actorRef",
    fieldClass: "identity",
    required: false,
    piiPolicy: "opaque_ref",
    notes: "Scoped internal reference or hash; never expose provider claims or raw profile identifiers in UI DTOs.",
  },
  {
    name: "actorDisplay",
    fieldClass: "identity",
    required: false,
    piiPolicy: "safe_label",
    notes: "Optional safe label such as owner, system, or internal agent label.",
  },
  {
    name: "sessionRef",
    fieldClass: "identity",
    required: false,
    piiPolicy: "hash_only",
    notes: "Hashed session correlation value, not a cookie, token, or raw claim.",
  },
  {
    name: "requestRef",
    fieldClass: "provenance",
    required: false,
    piiPolicy: "opaque_ref",
    notes: "Request correlation id for server-side diagnosis.",
  },
  {
    name: "ipAddressHash",
    fieldClass: "identity",
    required: false,
    piiPolicy: "hash_only",
    notes: "Hashed network address only; no raw address is exposed in app DTOs.",
  },
  {
    name: "userAgentHash",
    fieldClass: "identity",
    required: false,
    piiPolicy: "hash_only",
    notes: "Hashed user-agent string only; no raw browser string is exposed in app DTOs.",
  },
  {
    name: "moduleKey",
    fieldClass: "target",
    required: true,
    piiPolicy: "enum",
    notes: "Module or operating surface affected by the action.",
  },
  {
    name: "action",
    fieldClass: "action",
    required: true,
    piiPolicy: "enum",
    notes: "Stable dotted action name from the approved event family catalog.",
  },
  {
    name: "targetType",
    fieldClass: "target",
    required: true,
    piiPolicy: "enum",
    notes: "Resource type affected by the action.",
  },
  {
    name: "targetRef",
    fieldClass: "target",
    required: false,
    piiPolicy: "opaque_ref",
    notes: "Opaque object reference; UI DTOs must avoid raw private ids.",
  },
  {
    name: "targetDisplay",
    fieldClass: "target",
    required: false,
    piiPolicy: "safe_label",
    notes: "Short user-safe label only when it cannot leak private source material.",
  },
  {
    name: "result",
    fieldClass: "result",
    required: true,
    piiPolicy: "enum",
    notes: "Success, failure, blocked, dry-run, proposal, approval, rejection, or rollback state.",
  },
  {
    name: "riskLevel",
    fieldClass: "risk",
    required: true,
    piiPolicy: "enum",
    notes: "Risk level aligned to Personal OS high-risk module rules.",
  },
  {
    name: "approvalLevel",
    fieldClass: "approval",
    required: true,
    piiPolicy: "enum",
    notes: "Approval needed or completed for this action.",
  },
  {
    name: "humanApprovalRequired",
    fieldClass: "approval",
    required: true,
    piiPolicy: "enum",
    notes: "Boolean gate for finance, life, company, public output, external collaboration, and agent final writes.",
  },
  {
    name: "sourceKind",
    fieldClass: "source",
    required: true,
    piiPolicy: "enum",
    notes: "Server action, route handler, server loader, CLI proof, agent dry-run, manual review, or provider event.",
  },
  {
    name: "sourceRef",
    fieldClass: "source",
    required: false,
    piiPolicy: "opaque_ref",
    notes: "Evidence report, route, operation id, or provider event reference after redaction.",
  },
  {
    name: "agentRef",
    fieldClass: "agent",
    required: false,
    piiPolicy: "safe_label",
    notes: "Internal AgentFacts-lite label when an internal agent proposed or dry-ran the operation.",
  },
  {
    name: "operationId",
    fieldClass: "agent",
    required: false,
    piiPolicy: "safe_label",
    notes: "Agent operation id such as agent.ops.describe-contract or work.proof.preflight.",
  },
  {
    name: "proposalRef",
    fieldClass: "approval",
    required: false,
    piiPolicy: "opaque_ref",
    notes: "Reference to a proposal awaiting owner/admin review.",
  },
  {
    name: "proofRef",
    fieldClass: "provenance",
    required: false,
    piiPolicy: "safe_label",
    notes: "Relative generated proof path or immutable evidence pointer after redaction.",
  },
  {
    name: "beforeRef",
    fieldClass: "provenance",
    required: false,
    piiPolicy: "opaque_ref",
    notes: "Optional snapshot reference; do not store sensitive before-payloads inline.",
  },
  {
    name: "afterRef",
    fieldClass: "provenance",
    required: false,
    piiPolicy: "opaque_ref",
    notes: "Optional snapshot reference; do not store sensitive after-payloads inline.",
  },
  {
    name: "metadata",
    fieldClass: "redaction",
    required: false,
    piiPolicy: "json_redacted",
    notes: "Small validated JSON object after redaction; never a raw adapter payload or report body.",
  },
  {
    name: "redactionVersion",
    fieldClass: "redaction",
    required: true,
    piiPolicy: "safe_label",
    notes: "Version of the mapper/redaction policy used to create the event.",
  },
  {
    name: "retentionClass",
    fieldClass: "retention",
    required: true,
    piiPolicy: "enum",
    notes: "Retention class that determines future purge/export/review behavior.",
  },
  {
    name: "previousEventHash",
    fieldClass: "integrity",
    required: false,
    piiPolicy: "hash_only",
    notes: "Future hash-chain pointer for tamper-evidence after persistence is approved.",
  },
  {
    name: "eventHash",
    fieldClass: "integrity",
    required: false,
    piiPolicy: "hash_only",
    notes: "Future canonical hash of the redacted event envelope.",
  },
] as const satisfies readonly OperatingAuditEventField[]

export const OPERATING_AUDIT_EVENT_FAMILIES = [
  {
    ...STATIC_AUDIT_GUARDS,
    familyKey: "auth.session",
    moduleKeys: ["auth", "settings", "admin"],
    actions: ["auth.session.proof", "auth.profile.mapping", "auth.mock.boundary.checked"],
    actorTypes: ["owner", "system"],
    targetTypes: ["profile", "session", "owner_auth_boundary"],
    defaultRisk: "MEDIUM",
    defaultApprovalLevel: "owner_review",
    retentionClass: "security_1_year",
    exampleSourceKind: "cli_proof",
    sourceRefs: [
      "docs/08_acceptance-and-qa/ACC-005_supabase-session-proof-checklist.md",
      "docs/02_architecture-and-rules/AUT-005_owner-demo-account-boundary.md",
    ],
    nextTask: "AUTH-005",
    stopCondition:
      "Stop before claiming real owner auth until Supabase public env and signed-in auth status proof exist.",
  },
  {
    ...STATIC_AUDIT_GUARDS,
    familyKey: "work.mutation",
    moduleKeys: ["work"],
    actions: [
      "work.project.create",
      "work.task.update",
      "work.note.create",
      "work.deliverable.update",
      "work.refresh.proof",
    ],
    actorTypes: ["owner", "system", "internal_agent"],
    targetTypes: ["project", "project_task", "project_note", "project_deliverable", "proof_run"],
    defaultRisk: "MEDIUM",
    defaultApprovalLevel: "owner_review",
    retentionClass: "standard_180_days",
    exampleSourceKind: "server_action",
    sourceRefs: [
      "docs/02_architecture-and-rules/ARC-018_work-module-contract.md",
      "docs/08_acceptance-and-qa/ACC-004_work-refresh-proof-harness.md",
    ],
    nextTask: "WORK-009",
    stopCondition:
      "Stop before valuable Work writes when no approved disposable proof target and write confirmation exist.",
  },
  {
    ...STATIC_AUDIT_GUARDS,
    familyKey: "ai-input.source-workflow",
    moduleKeys: ["ai-input"],
    actions: [
      "ai-input.source.connection.reviewed",
      "ai-input.source.workflow.started",
      "ai-input.proposal.created",
      "ai-input.write-intent.reviewed",
    ],
    actorTypes: ["owner", "system", "internal_agent", "external_service"],
    targetTypes: ["source_connection", "source_asset", "ai_workflow_run", "module_write_intent"],
    defaultRisk: "HIGH",
    defaultApprovalLevel: "human_required",
    retentionClass: "security_1_year",
    exampleSourceKind: "server_component_loader",
    sourceRefs: [
      "docs/02_architecture-and-rules/DBS-002_source-workflow-schema-contract.md",
      "docs/02_architecture-and-rules/ARC-027_ai-input-formal-readiness-bff.md",
    ],
    nextTask: "DATTR-024-SPLIT",
    stopCondition:
      "Stop before connector runtime, schema migration, external sync, or final module writes without approval.",
  },
  {
    ...STATIC_AUDIT_GUARDS,
    familyKey: "agent.operation",
    moduleKeys: ["agent-team-os", "workflow", "work"],
    actions: [
      "agent.operation.dry-run.requested",
      "agent.operation.proposal.created",
      "agent.operation.approved",
      "agent.registry.readiness.checked",
    ],
    actorTypes: ["owner", "internal_agent", "system"],
    targetTypes: ["agent_operation", "agent_manifest", "approval_request", "proof_run"],
    defaultRisk: "HIGH",
    defaultApprovalLevel: "human_required",
    retentionClass: "security_1_year",
    exampleSourceKind: "agent_dry_run",
    sourceRefs: [
      "docs/02_architecture-and-rules/ARC-028_nanda-agent-protocol-alignment.md",
      "docs/02_architecture-and-rules/ARC-029_agent-operation-dry-run-contract.md",
    ],
    nextTask: "AGENT-OPS-API-001",
    stopCondition:
      "Stop before protected runtime API, autonomous execution, public registry, or external registration without auth, trust, audit, rollback, and approval.",
  },
  {
    ...STATIC_AUDIT_GUARDS,
    familyKey: "client-portal.public-access",
    moduleKeys: ["client-portal"],
    actions: [
      "client-portal.token.created",
      "client-portal.token.rotated",
      "client-portal.token.revoked",
      "client-portal.public-access.allowed",
      "client-portal.public-access.denied",
    ],
    actorTypes: ["owner", "public_token", "system"],
    targetTypes: ["share_token", "client_visible_project_view", "file_access", "public_route"],
    defaultRisk: "HIGH",
    defaultApprovalLevel: "human_required",
    retentionClass: "security_1_year",
    exampleSourceKind: "route_handler",
    sourceRefs: [
      "docs/02_architecture-and-rules/DBS-004_client-portal-token-schema-contract.md",
      "docs/02_architecture-and-rules/AUT-004_client-portal-public-storage-policy.md",
    ],
    nextTask: "CLIENT-005",
    stopCondition:
      "Stop before token lifecycle writes, public output expansion, file URL rendering, or public smoke without schema/action approval.",
  },
  {
    ...STATIC_AUDIT_GUARDS,
    familyKey: "high-risk.proposal",
    moduleKeys: ["life", "finance", "company", "chamber", "workflow"],
    actions: [
      "high-risk.proposal.created",
      "high-risk.proposal.approved",
      "high-risk.proposal.rejected",
      "high-risk.export.requested",
      "high-risk.boundary.changed",
    ],
    actorTypes: ["owner", "internal_agent", "system"],
    targetTypes: ["proposal", "private_record", "export", "boundary_policy"],
    defaultRisk: "CRITICAL",
    defaultApprovalLevel: "human_required",
    retentionClass: "high_risk_7_year_review_required",
    exampleSourceKind: "manual_review",
    sourceRefs: [
      "docs/02_architecture-and-rules/ARC-013_module-map.md",
      "docs/02_architecture-and-rules/ARC-019_agent-boundary-policy.md",
    ],
    nextTask: "HIGH-RISK-DRAFT-001",
    stopCondition:
      "Stop before finance, life, company, public output, or external collaboration final writes without explicit human approval.",
  },
  {
    ...STATIC_AUDIT_GUARDS,
    familyKey: "admin.operator",
    moduleKeys: ["admin", "settings", "deployment"],
    actions: [
      "admin.evidence.reviewed",
      "settings.permission.proposed",
      "deployment.marker.reviewed",
      "operator.export.requested",
    ],
    actorTypes: ["owner", "system"],
    targetTypes: ["evidence_report", "permission_snapshot", "deployment_marker", "audit_export"],
    defaultRisk: "MEDIUM",
    defaultApprovalLevel: "admin_review",
    retentionClass: "standard_180_days",
    exampleSourceKind: "server_component_loader",
    sourceRefs: [
      "docs/02_architecture-and-rules/ARC-026_admin-settings-audit-bff.md",
      "docs/08_acceptance-and-qa/ACC-003_launch-proof-checklist.md",
    ],
    nextTask: "DEPLOY-002",
    stopCondition:
      "Stop before admin mutations, permission writes, provider writes, exports, or deployment changes without a reviewed write contract.",
  },
] as const satisfies readonly OperatingAuditEventFamily[]

export const OPERATING_AUDIT_BFF_CONTRACT = {
  id: "AUDIT-OPS-001",
  status: "read_contract_proposal_only",
  futureReadSurface: "protected_admin_settings_records_audit",
  filters: [
    "occurredAtRange",
    "actorType",
    "moduleKey",
    "action",
    "result",
    "riskLevel",
    "approvalLevel",
    "sourceKind",
  ],
  redactedDtoFields: [
    "id",
    "occurredAt",
    "actorType",
    "actorDisplay",
    "moduleKey",
    "action",
    "targetType",
    "targetDisplay",
    "result",
    "riskLevel",
    "approvalLevel",
    "sourceKind",
    "agentRef",
    "operationId",
    "proofRef",
    "retentionClass",
  ],
  prohibitedDtoFields: [
    "raw provider claims",
    "raw profile identifiers",
    "cookies",
    "session secrets",
    "public token verifier values",
    "database connection strings",
    "database hostnames",
    "raw network addresses",
    "raw browser strings",
    "private report bodies",
    "raw adapter payloads",
  ],
  authorizationBoundary:
    "requireUser() plus owner/admin service-layer authorization before any future read or export.",
  writeBoundary:
    "No route handler, server action, schema migration, seed, database read, database write, export, or admin mutation is implemented by this contract.",
  exportBoundary:
    "Future export requires owner/admin authorization, date range, redacted DTO mapper, and separate approval for high-risk modules.",
  schemaWriteAllowed: false,
  runtimeWriteAllowed: false,
  publicOutputExpansion: false,
} as const

export const OPERATING_AUDIT_CONTRACT_SUMMARY = {
  id: "AUDIT-OPS-001",
  version: "0.1.0",
  status: "ready_for_schema_review",
  appendOnlyRequired: true,
  tamperEvidenceRecommended: true,
  schemaWriteAllowed: false,
  runtimeWriteAllowed: false,
  publicOutputExpansion: false,
  fieldCount: OPERATING_AUDIT_EVENT_FIELDS.length,
  familyCount: OPERATING_AUDIT_EVENT_FAMILIES.length,
  requiredNextTasks: [
    "AUTH-005",
    "WORK-009",
    "DATTR-024-SPLIT",
    "CLIENT-005",
    "AGENT-OPS-001",
    "DEPLOY-002",
  ],
  sourceRefs: [
    "docs/02_architecture-and-rules/DBS-006_operating-audit-event-schema-contract.md",
    "docs/02_architecture-and-rules/DBS-005_per-module-real-data-migration-matrix.md",
    "docs/02_architecture-and-rules/ARC-026_admin-settings-audit-bff.md",
    "docs/02_architecture-and-rules/ARC-029_agent-operation-dry-run-contract.md",
    "docs/08_acceptance-and-qa/ACC-002_module-acceptance-criteria.md",
  ],
} as const
