import assert from "node:assert/strict"
import { createOperatingState } from "../src/lib/ui-data/yuanzhan/fixtures"
import { parseUiDataMode } from "../src/lib/ui-data/yuanzhan/mode"
import { canRead, canEdit, putRecord, removeRecord, updateProgress, visibleRecords, freezeEvidence, reconcileRecords } from "../src/lib/ui-data/yuanzhan/commands"
import { evaluateFormula } from "../src/lib/ui-data/yuanzhan/formulas"
import { workMetrics } from "../src/lib/ui-data/yuanzhan/metrics"
import type { OperatingRecord } from "../src/types/yuanzhan-ui"
const checks: string[] = []
function check(name: string, fn: () => void) { fn(); checks.push(name) }
const full = createOperatingState("showcase"), empty = createOperatingState("empty")
const now = "2026-09-13T12:00:00Z"
check("mode: explicit showcase/empty, default empty, invalid fails", () => { assert.equal(parseUiDataMode(undefined), "empty"); assert.equal(parseUiDataMode(""), "empty"); assert.equal(parseUiDataMode("showcase"), "showcase"); assert.equal(parseUiDataMode("empty"), "empty"); assert.throws(() => parseUiDataMode("true")) })
check("empty has zero business/audit/dismissed records", () => { assert.deepEqual(empty.records, []); assert.deepEqual(empty.activity, []); assert.deepEqual(empty.dismissedSignals, []) })
check("fixture factories are independent and deterministic", () => { assert.deepEqual(full, createOperatingState("showcase")); const copy = createOperatingState("showcase"); copy.records[0].title = "changed"; assert.notEqual(copy.records[0].title, full.records[0].title) })
check("showcase graph references and version pointers resolve", () => { for (const r of full.records) { for (const id of [...(r.refs ?? []), ...(r.fileIds ?? []), ...[r.projectId, r.parentId, r.goalId].filter(Boolean)]) assert(full.records.some(x => x.id === id), `${r.id} -> ${id}`); for (const e of r.entries ?? []) assert(full.records.find(x => x.id === e.fileId)?.versions?.some(v => v.id === e.versionId)) } })
check("personal, restricted project and payroll preview visibility", () => { assert(!visibleRecords(full, "lily", "team").some(r => r.id === "project-3" || r.id === "journal-private" || r.id === "payroll-1")); assert(visibleRecords(full, "lily", "team").some(r => r.id === "payroll-2")); assert(!visibleRecords(full, "lily", "personal").length); assert(visibleRecords(full, "yuxing", "personal").length) })
check("author body and assignee progress are distinct", () => { const t = full.records.find(r => r.id === "task-1")!; assert(!canEdit(t, "lily")); assert.throws(() => putRecord(full, { ...t, title: "other edited" }, "lily", now)); const next = updateProgress(full, t.id, "lily", "完成", "2026-09-13"); assert.equal(next.records.find(r => r.id === t.id)?.completed, "2026-09-13"); assert.equal(next.records.find(r => r.id === "journal-1")?.refs?.[0], t.id) })
check("administrator cannot edit another author's journal", () => { const r = full.records.find(r => r.id === "journal-2")!; assert.throws(() => putRecord(full, { ...r, body: "edited" }, "yuxing", now)) })
check("first create/edit/delete restores empty records", () => { const record: OperatingRecord = { id: "first", kind: "journal", title: "第一篇", body: "即時文字", date: "2026-09-13", space: "team", author: "lily", visibility: "team" }; const created = putRecord(empty, record, "lily", now); assert(canRead(created.records[0], "yuxing", created.records)); const edited = putRecord(created, { ...record, body: "第二版" }, "lily", now); assert.equal(edited.records[0].body, "第二版"); assert.equal(removeRecord(edited, record.id, "lily").records.length, 0) })
check("invalid titles, references and illegal reassignment are rejected", () => { const task = full.records.find(r => r.id === "task-1")!; assert.throws(() => putRecord(full, { ...task, title: "" }, "yuxing", now)); assert.throws(() => putRecord(full, { ...task, refs: ["missing"] }, "yuxing", now)); assert.throws(() => putRecord(full, { ...task, author: "lily" }, "yuxing", now)); assert.throws(() => putRecord(full, { ...task, started: "2026-09-14", completed: "2026-09-13" }, "yuxing", now)) })
check("comments inherit the parent read boundary", () => { const parent = full.records.find(r => r.id === "project-3")!; const comment: OperatingRecord = { id: "comment-restricted", kind: "comment", title: "secret", date: "2026-09-13", author: "yuxing", space: "team", visibility: "team", parentId: parent.id }; assert(!canRead(comment, "lily", [...full.records, comment])); assert.throws(() => putRecord(full, { ...comment, author: "lily" }, "lily", now)) })
check("linked deletions block; snapshot content cannot drift", () => { assert.throws(() => removeRecord(full, "task-1", "yuxing")); assert.throws(() => removeRecord(full, "file-1", "yuxing")); const repo = full.records.find(r => r.id === "evidence-1")!; const frozen = freezeEvidence(repo, full, "2026-09-13"); const text = frozen.snapshots.at(-1)!.entries[0].text; const copy = createOperatingState("showcase"); copy.records.find(r => r.id === "file-1")!.versions![0].text = "changed"; assert.equal(frozen.snapshots.at(-1)!.entries[0].text, text); assert.throws(() => freezeEvidence({ ...repo, readme: "" }, full, "2026-09-13")) })
check("formula arithmetic, references and aggregates", () => { assert.equal(evaluateFormula("=(2+3)*4").value, 20); const cells = { B1: 2, C1: 600, D1: "=B1*C1", D2: 800 }; assert.equal(evaluateFormula("=SUM(D1:D2)", cells).value, 2000); assert.equal(evaluateFormula("=AVERAGE(D1,D2)", cells).value, 1000); assert.equal(evaluateFormula("=MAX(2,MIN(5,3))").value, 3) })
check("formula invalid refs, cycles, divide-by-zero and script input fail", () => { assert.equal(evaluateFormula("=D99").error, "#REF!"); assert.equal(evaluateFormula("=D1", { D1: "=D2", D2: "=D1" }).error, "#CYCLE!"); assert.equal(evaluateFormula("=2/0").error, "#DIV/0!"); assert(evaluateFormula('=alert("x")').error); assert.equal(evaluateFormula("").value, null) })
check("flow metrics use completed records and show insufficiency", () => { const blank = workMetrics(empty.records, "lily", "M"); assert.equal(blank.p50, null); assert(!blank.forecastReady); const metrics = workMetrics(visibleRecords(full, "lily", "team"), "lily", "M"); assert(metrics.count >= 8); assert(metrics.weeks >= 4); assert(metrics.forecastReady); assert(metrics.p85! >= metrics.p50!) })
check("calendar rejects impossible dates and retains obligation events", () => { const event = full.records.find(r => r.id === "event-2")!; assert.throws(() => putRecord(full, { ...event, date: "2026-02-31" }, "yuxing", now)); assert.throws(() => removeRecord(full, "event-1", "yuxing")) })
check("manager pairs visible member transactions without editing authorship", () => { const source = full.records.find(r => r.kind === "transaction")!; const bank = full.records.find(r => r.kind === "bank")!; const state = { ...full, records: full.records.map(r => r.id === source.id ? { ...r, author: "lily" as const, matchedId: undefined } : r.id === bank.id ? { ...r, matchedId: undefined } : r) }; const paired = reconcileRecords(state, bank.id, source.id, "yuxing", "已對帳", now); assert.equal(paired.records.find(r => r.id === source.id)?.author, "lily"); assert.throws(() => reconcileRecords(state, bank.id, source.id, "lily", "已對帳", now)); assert.throws(() => reconcileRecords(paired, bank.id, source.id, "yuxing", "已對帳", now)); const cleared = reconcileRecords(paired, bank.id, source.id, "yuxing", "待對帳", now); assert.equal(cleared.records.find(r => r.id === source.id)?.matchedId, undefined) })
check("repeated formula dependencies share bounded computation", () => { const cells: Record<string, string> = { D1: "1" }; for (let i = 2; i <= 90; i++) cells[`D${i}`] = `=D${i - 1}+D${i - 1}`; assert.equal(evaluateFormula("=D90", cells).value, 2 ** 89) })
console.log(JSON.stringify({ task: "YZUI-002..010", result: "PASS", checks: checks.length, details: checks, scope: "UI-only contract; no DB/provider/network writes" }, null, 2))
