import "server-only"

import { getSupabasePublicConfig } from "@/lib/supabase/env"
import { buildAIInputSourceWorkflowProofBootstrapContract } from "@/lib/services/ai-input-source-workflow-proof-bootstrap-readiness.service"
import type {
  AIInputFormalReadinessContract,
  AIInputSourceControlMatrixRow,
  AIInputSourceWorkflowGateMatrixRow,
  AIInputSourceWorkflowReadModel,
} from "@/types/ai-input-readiness"

export async function buildAIInputFormalReadinessContract(): Promise<AIInputFormalReadinessContract> {
  const hasSupabasePublicConfig = Boolean(getSupabasePublicConfig())
  const generatedAt = new Date().toISOString()
  const sourceWorkflowProofBootstrap = await buildAIInputSourceWorkflowProofBootstrapContract({ generatedAt })
  const sourceWorkflowModels: AIInputSourceWorkflowReadModel[] = [
    {
      kind: "source_connection",
      label: "SourceConnection",
      statusLabel: "Not persisted",
      state: "not_persisted",
      count: null,
      description: "External provider connections, consent state, sync cadence, scope, and permission status.",
      emptyState: "Formal mode has no Supabase-backed SourceConnection rows yet.",
      nextGate: "DATTR-024B must review schema and service authorization before loader reads appear.",
      auditRefs: ["AUDIT-OPS-001", "ai-input.source-workflow"],
      sourceRefs: ["ARC-031", "DBS-002", "AUT-001"],
      tone: "blocked",
    },
    {
      kind: "source_asset",
      label: "SourceAsset",
      statusLabel: "Not persisted",
      state: "not_persisted",
      count: null,
      description: "Normalized source assets, raw source item references, snapshots, and safe evidence metadata.",
      emptyState: "Formal mode has no persisted SourceAsset registry and exposes no raw provider payloads.",
      nextGate: "DATTR-024B must reconcile SourceAsset fields with retention and redaction rules.",
      auditRefs: ["AUDIT-OPS-001", "ai-input.source-workflow"],
      sourceRefs: ["ARC-031", "DBS-002", "AUT-001"],
      tone: "blocked",
    },
    {
      kind: "ai_workflow_run",
      label: "AIWorkflowRun",
      statusLabel: "Not persisted",
      state: "not_persisted",
      count: null,
      description: "Workflow run shell for source sync, recognition, organizing, review, and brief preparation steps.",
      emptyState: "Formal AI 工作台 has no Supabase-backed AIWorkflowRun rows yet.",
      nextGate: "DATTR-024B must define run, step, event, and audit mapping before DB reads.",
      auditRefs: ["AUDIT-OPS-001", "ai-input.source-workflow"],
      sourceRefs: ["ARC-031", "DBS-002", "DBS-006"],
      tone: "blocked",
    },
    {
      kind: "ai_work_item",
      label: "AIWorkItem",
      statusLabel: "Not persisted",
      state: "not_persisted",
      count: null,
      description: "Reviewable AI work items created from uncertain, risky, or owner-confirmation-needed source results.",
      emptyState: "Formal mode has no persisted AIWorkItem review queue and shows no mock review cards.",
      nextGate: "DATTR-024B must define owner-visible queue fields, authz, and audit events.",
      auditRefs: ["AUDIT-OPS-001", "ai-input.source-workflow"],
      sourceRefs: ["ARC-031", "DBS-002", "DBS-006"],
      tone: "blocked",
    },
    {
      kind: "data_unit_proposal",
      label: "DataUnitProposal",
      statusLabel: "Schema review required",
      state: "schema_review_required",
      count: null,
      description: "Composite source-derived proposal that can become a module-ready data unit only after owner review.",
      emptyState: "Formal mode has no persisted DataUnitProposal list and exposes no fake proposal records.",
      nextGate: "DATTR-024B must define proposal payload shape, source IDs, redaction, and approval state.",
      auditRefs: ["AUDIT-OPS-001", "ai-input.source-workflow"],
      sourceRefs: ["ARC-031", "DBS-002", "DBS-006"],
      tone: "warn",
    },
    {
      kind: "module_write_intent",
      label: "ModuleWriteIntent",
      statusLabel: "Blocked by design",
      state: "blocked_by_design",
      count: null,
      description: "Owner-reviewed proposal boundary before source-derived output can request a module write.",
      emptyState: "Formal mode cannot write module records and has no persisted ModuleWriteIntent queue yet.",
      nextGate: "DATTR-024D must add owner-reviewed proposal actions after schema and proof gates pass.",
      auditRefs: ["AUDIT-OPS-001", "ai-input.source-workflow"],
      sourceRefs: ["ARC-031", "DBS-006", "ARC-028"],
      tone: "warn",
    },
  ]
  const sourceControlRows: AIInputSourceControlMatrixRow[] = [
    {
      id: "formal-manual-import",
      source: "Manual import and local files",
      provider: "Manual",
      connectorType: "Upload",
      connectionStatus: "planned",
      syncStatus: "not_configured",
      inputMode: "manual",
      inputModeLabel: "Manual",
      riskLevel: "variable",
      riskLabel: "By source",
      scope: "Owner-selected images, audio, Markdown, links, and batch files.",
      cadence: "Owner-triggered",
      defaultModule: "AI triage",
      lastSync: "Unavailable",
      nextSync: "After DATTR-024 persistence approval",
      reviewRule: "High-risk or unclear module routing requires owner review.",
      nextAction: "Keep as UI-only capture until SourceAsset persistence is approved.",
      missingPermissions: null,
      boundary:
        "No file upload runtime, OCR, transcription, provider fetch, or Supabase write is enabled by this matrix.",
      auditRefs: ["ai-input.source-workflow.asset.blocked", "ai-input.source-workflow.proposal.reviewed"],
      tone: "warn",
    },
    {
      id: "formal-line-chamber",
      source: "LINE chamber messages",
      provider: "LINE",
      connectorType: "Messaging",
      connectionStatus: "planned",
      syncStatus: "not_configured",
      inputMode: "scheduled",
      inputModeLabel: "Scheduled",
      riskLevel: "medium",
      riskLabel: "Medium",
      scope: "Recent messages, attachments, and links after explicit owner authorization.",
      cadence: "Planned daily window",
      defaultModule: "Chamber",
      lastSync: "Unavailable",
      nextSync: "After connector consent and proof target approval",
      reviewRule: "Personal data and relationship context require owner review before proposal output.",
      nextAction: "Complete connector consent/runtime approval before any provider read.",
      missingPermissions: "LINE consent, scoped messaging access, approved retention policy",
      boundary:
        "DATTR-024E keeps OAuth, webhook, polling, provider API calls, and raw adapter payloads blocked.",
      auditRefs: ["ai-input.connector.consent.grant", "ai-input.provider-event.verify"],
      tone: "blocked",
    },
    {
      id: "formal-google-docs-work",
      source: "Google Docs project documents",
      provider: "Google Docs",
      connectorType: "Document",
      connectionStatus: "planned",
      syncStatus: "not_configured",
      inputMode: "event",
      inputModeLabel: "Event",
      riskLevel: "medium",
      riskLabel: "Medium",
      scope: "Approved document list and future document-change events.",
      cadence: "Provider event after approval",
      defaultModule: "Work",
      lastSync: "Unavailable",
      nextSync: "After adapter and service authorization approval",
      reviewRule: "External sharing or client-visible summaries require explicit approval.",
      nextAction: "Define provider adapter and owner-scoped BFF reads after AUTH-005/WORK-009.",
      missingPermissions: "Drive/Docs read scope, provider event verification",
      boundary:
        "No Google provider client, webhook route, polling job, document body fetch, or Work write exists in this slice.",
      auditRefs: ["ai-input.provider-event.receive", "ai-input.source-workflow.write-intent.blocked"],
      tone: "blocked",
    },
    {
      id: "formal-rss-research",
      source: "RSS research feeds",
      provider: "RSS",
      connectorType: "Feed",
      connectionStatus: "planned",
      syncStatus: "not_configured",
      inputMode: "polling",
      inputModeLabel: "Polling",
      riskLevel: "low",
      riskLabel: "Low",
      scope: "Public feed entries, links, and citation metadata after fetch policy approval.",
      cadence: "Planned daily poll",
      defaultModule: "Research",
      lastSync: "Unavailable",
      nextSync: "After polling runtime approval",
      reviewRule: "Only high-relevance summaries may become DataUnitProposal candidates.",
      nextAction: "Keep polling disabled until connector runtime and retention rules are approved.",
      missingPermissions: "Polling runtime approval",
      boundary:
        "No URL fetching, feed polling, citation extraction, or Research persistence is enabled.",
      auditRefs: ["ai-input.source.workflow.started", "ai-input.proposal.created"],
      tone: "blocked",
    },
    {
      id: "formal-gmail-client",
      source: "Gmail client threads",
      provider: "Gmail",
      connectorType: "Email",
      connectionStatus: "planned",
      syncStatus: "not_configured",
      inputMode: "polling",
      inputModeLabel: "Polling",
      riskLevel: "high",
      riskLabel: "High",
      scope: "Client threads and attachments only after public-output and token policy review.",
      cadence: "Not scheduled",
      defaultModule: "Work",
      lastSync: "Unavailable",
      nextSync: "Blocked until client/public-output gates are approved",
      reviewRule: "Client Portal, financial, personal, or confidential content must fail closed.",
      nextAction: "Do not implement before auth/session, audit, public-output, and approval gates pass.",
      missingPermissions: "gmail.readonly scope, client-output policy, audit storage approval",
      boundary:
        "No email provider access, attachment read, public output, Client Portal write, or module final write is allowed.",
      auditRefs: ["ai-input.connector.scope.review", "ai-input.provider-event.block"],
      tone: "blocked",
    },
    {
      id: "formal-github-markdown",
      source: "GitHub repo and Markdown references",
      provider: "GitHub",
      connectorType: "Repo files",
      connectionStatus: "planned",
      syncStatus: "not_configured",
      inputMode: "one_time",
      inputModeLabel: "One-time",
      riskLevel: "medium",
      riskLabel: "Medium",
      scope: "Docs, references, AGENTS, and SKILL files selected by the owner.",
      cadence: "Owner-triggered import/export",
      defaultModule: "Agent Team OS",
      lastSync: "Unavailable",
      nextSync: "After import/export workflow approval",
      reviewRule: "Repo changes are proposal-only; never silently overwrite governance files.",
      nextAction: "Create an import/export proposal flow only after audit and rollback boundaries exist.",
      missingPermissions: "repo read scope for private repositories",
      boundary:
        "No GitHub API call, repository write, agent registration, or governance-file overwrite is enabled.",
      auditRefs: ["ai-input.write-intent.review", "ai-input.write-intent.request_changes"],
      tone: "blocked",
    },
    {
      id: "formal-telegram-research",
      source: "Telegram research discussion",
      provider: "Telegram",
      connectorType: "Messaging",
      connectionStatus: "needs_setup",
      syncStatus: "not_configured",
      inputMode: "webhook",
      inputModeLabel: "Webhook",
      riskLevel: "high",
      riskLabel: "High",
      scope: "Discussion messages only after bot, endpoint, replay, and retention review.",
      cadence: "Not scheduled",
      defaultModule: "Research",
      lastSync: "Unavailable",
      nextSync: "Blocked until webhook runtime approval",
      reviewRule: "Private group messages require redaction and explicit owner review.",
      nextAction: "Do not create webhook endpoints before endpoint/auth/replay policy is approved.",
      missingPermissions: "Bot token, webhook endpoint, replay protection, retention approval",
      boundary:
        "No webhook route, bot token use, event receive, message read, or provider payload exposure is allowed.",
      auditRefs: ["ai-input.provider-event.reject_replay", "ai-input.connector.retention.delete_request"],
      tone: "blocked",
    },
  ]
  const sourceControlConnectedCount = sourceControlRows.filter((row) => row.connectionStatus === "connected").length
  const sourceControlPlannedCount = sourceControlRows.filter((row) => row.connectionStatus === "planned").length
  const sourceControlNeedsSetupCount = sourceControlRows.filter((row) => row.connectionStatus === "needs_setup").length
  const sourceControlHighRiskCount = sourceControlRows.filter((row) => row.riskLevel === "high").length
  const sourceControlMissingPermissionCount = sourceControlRows.filter((row) => row.missingPermissions).length
  const sourceWorkflowGateRows: AIInputSourceWorkflowGateMatrixRow[] = [
    {
      id: "DATTR-024H-MIGRATION-DRAFT",
      gateLabel: "Create-only migration draft",
      state: "complete",
      statusLabel: "complete",
      signal: "Review-only Prisma schema and SQL draft exist for Source Workflow objects.",
      ownerRunCommand: "pnpm ai-input:migration-draft:check",
      allowedNow: "Inspect draft schema, migration README, and no-apply SQL.",
      blockedRuntime: "Migration apply, seed changes, DB reads, DB writes, and persisted audit rows.",
      nextAction: "Keep migration apply in Manual Ops until identity, RLS, audit storage, and proof target are approved.",
      boundary: "No deployable prisma/migrations entry is created by this surface.",
      tone: "good",
    },
    {
      id: "DATTR-024I-PROOF-RUNNER",
      gateLabel: "Dry-run proof runner",
      state: "dry_run_only",
      statusLabel: "dry-run only",
      signal: "Proof runner can emit no-secret readiness packets and refuses writes without explicit target confirmations.",
      ownerRunCommand: "pnpm ai-input:proof-runner:check && pnpm ai-input:proof -- --json",
      allowedNow: "Run dry-run proof classification and inspect the generated no-secret packet.",
      blockedRuntime: "Default DATABASE_URL writes, migration apply, and test data writes without owner-approved env gates.",
      nextAction: "Owner may supply a disposable proof target later; until then this remains dry-run.",
      boundary: "The UI does not execute the runner or reveal target URLs.",
      tone: "warn",
    },
    {
      id: "DATTR-024N-SOURCE-WORKFLOW-LOCAL-PROOF-BOOTSTRAP",
      gateLabel: "Local proof bootstrap",
      state: sourceWorkflowProofBootstrap.summary.canRunChildProof ? "ready_boundary" : "dry_run_only",
      statusLabel: sourceWorkflowProofBootstrap.summary.packetStatus,
      signal: `DATTR-024P latest proof evidence resolver (DATTR-024P-SOURCE-WORKFLOW-LATEST-PROOF-EVIDENCE-RESOLVER) selected ${sourceWorkflowProofBootstrap.latestEvidence.latest.latestPacketPath}; freshness is ${sourceWorkflowProofBootstrap.latestEvidence.latest.freshness}; checker is ${sourceWorkflowProofBootstrap.summary.checkerStatus}; target provided ${sourceWorkflowProofBootstrap.summary.targetProvided ? "yes" : "no"}; host class ${sourceWorkflowProofBootstrap.summary.hostClass}.`,
      ownerRunCommand:
        "pnpm ai-input:proof-evidence:check && pnpm ai-input:proof-local:check && pnpm ai-input:proof-local -- --json",
      allowedNow: "Inspect packet status, target classification, missing prerequisites, child command, and no-secret safety flags.",
      blockedRuntime:
        "UI shell command execution, DB connection, migration apply, proof writes, connector runtime, provider calls, public output, and external registration.",
      nextAction:
        sourceWorkflowProofBootstrap.latestEvidence.latest.nextOwnerAction ??
        sourceWorkflowProofBootstrap.ownerActions[0] ??
        "Run pnpm ai-input:proof-local after selecting an explicit local/disposable proof target.",
      boundary:
        "Latest proof evidence is resolved from whitelisted generated no-secret packet paths only; target URL, host, credentials, raw packet body, and row IDs stay hidden.",
      tone: sourceWorkflowProofBootstrap.summary.canRunChildProof ? "warn" : "blocked",
    },
    {
      id: "DATTR-024Q-SOURCE-WORKFLOW-PROOF-TARGET-HANDOFF-SURFACE",
      gateLabel: "Proof target handoff",
      state:
        sourceWorkflowProofBootstrap.proofTargetHandoff.missingPrerequisites.length === 0
          ? "ready_boundary"
          : "dry_run_only",
      statusLabel: sourceWorkflowProofBootstrap.proofTargetHandoff.status,
      signal: `Protected owner handoff lists ${
        sourceWorkflowProofBootstrap.proofTargetHandoff.envVarNames.length
      } env var names, ${
        sourceWorkflowProofBootstrap.proofTargetHandoff.proofCommands.length
      } commands, ${
        sourceWorkflowProofBootstrap.proofTargetHandoff.evidenceTargets.length
      } evidence targets, and ${
        sourceWorkflowProofBootstrap.proofTargetHandoff.stopConditions.length
      } stop conditions without exposing target values.`,
      ownerRunCommand:
        "pnpm ai-input:proof-evidence:check && pnpm ai-input:proof-local:check && pnpm ai-input:proof-local -- --json",
      allowedNow:
        "Inspect owner action, env var names, proof commands, evidence output paths, pass/fail signals, missing prerequisites, and stop conditions.",
      blockedRuntime:
        "UI command execution, DB connection, DB write, migration apply, connector runtime, provider calls, public output, external agent database access, and external registration.",
      nextAction: sourceWorkflowProofBootstrap.proofTargetHandoff.ownerAction,
      boundary:
        "DATTR-024Q is a no-secret owner-run handoff only; it must not claim launch progress until owner/operator evidence exists.",
      tone:
        sourceWorkflowProofBootstrap.proofTargetHandoff.missingPrerequisites.length === 0
          ? "warn"
          : "blocked",
    },
    {
      id: "DATTR-024J-SERVICE-AUTHZ-RUNTIME",
      gateLabel: "Service authorization runtime boundary",
      state: "ready_boundary",
      statusLabel: "boundary ready",
      signal: "Server-only service calls requireUser(), maps operation contracts, and keeps runtime DB reads/writes disabled.",
      ownerRunCommand: "pnpm ai-input:service-runtime:check",
      allowedNow: "Inspect protected service DTO shape and operation authorization boundaries.",
      blockedRuntime: "Route handlers, server actions, Prisma clients, provider reads, DB reads, and DB writes.",
      nextAction: "Use this service boundary before any future BFF loader/action can touch persisted Source Workflow rows.",
      boundary: "Client Components receive UI-safe DTOs only.",
      tone: "good",
    },
    {
      id: "DATTR-024K-RLS-AUDIT-STORAGE",
      gateLabel: "RLS and audit storage review",
      state: "human_approval_required",
      statusLabel: "approval required",
      signal: "Identity strategy, default-deny RLS policy review, persisted audit storage, and redacted audit DTOs are documented.",
      ownerRunCommand: "pnpm ai-input:rls-audit-storage:check",
      allowedNow: "Review policy matrix, audit storage shape, and cross-owner proof requirements.",
      blockedRuntime: "RLS policy apply, audit storage writes, DB reads/writes, and any valuable database proof.",
      nextAction: "Select identity strategy and proof cases before enabling DB-backed Source Workflow runtime.",
      boundary:
        "identityStrategySelected=false; rlsPolicyApplyAllowed=false; auditStorageRuntimeAllowed=false; runtime remains off.",
      tone: "warn",
    },
    {
      id: "DATTR-024L-CONNECTOR-RUNTIME",
      gateLabel: "Connector runtime approval",
      state: "human_approval_required",
      statusLabel: "approval required",
      signal: "Connector provider inventory, consent, PKCE, webhook signature/replay, polling, redaction, and rollback gates are ready for review.",
      ownerRunCommand: "pnpm ai-input:connector-runtime:check",
      allowedNow: "Review connector approval gates and provider family risk inventory.",
      blockedRuntime: "OAuth callbacks, webhooks, polling jobs, provider API calls, file ingestion, secret writes, and raw adapter payloads.",
      nextAction: "Keep runtimeApprovalSelected=false until owner approval, proof target, RLS/audit, and rollback are accepted.",
      boundary:
        "runtimeApprovalSelected=false; connectorRuntimeAllowed=false; oauthRuntimeAllowed=false; webhookRuntimeAllowed=false.",
      tone: "warn",
    },
    {
      id: "DATTR-024-FORMAL-CUTOVER",
      gateLabel: "Full formal persistence cutover",
      state: "blocked",
      statusLabel: "blocked",
      signal: "Formal DB-backed Source Workflow still needs approved migration apply, proof target, authz, RLS/audit, connector runtime approval, and owner evidence.",
      ownerRunCommand: "pnpm ai-input:ops-surface:check",
      allowedNow: "Inspect the current gate matrix and continue post-30 research-to-task routing.",
      blockedRuntime: "Any DB-backed AI Input persistence, module final writes, public output expansion, external agent DB access, and external registration.",
      nextAction: "Run LOOP-118 research cadence or AUTH-005/WORK-009 if proof prerequisites appear.",
      boundary: "externalRegisterable remains false.",
      tone: "blocked",
    },
  ]

  return {
    id: "DATTR-025",
    status: "readiness_contract_active",
    generatedAt,
    mode: "formal_bff_contract",
    supabase: {
      publicConfig: hasSupabasePublicConfig ? "configured" : "missing",
    },
    persistence: {
      current: "not_persisted",
      futureGate:
        "DATTR-024 must review staged schema migration, service authorization, seed policy, connector security, and reachable DB proof before formal AI Input persistence is enabled.",
    },
    counts: {
      sourceConnections: null,
      sourceAssets: null,
      aiWorkflowRuns: null,
      aiWorkItems: null,
      dataUnitProposals: null,
      moduleWriteIntents: null,
    },
    prohibitedRuntime: [
      "Prisma schema changes",
      "migration apply",
      "Supabase writes",
      "connector runtime",
      "URL fetching",
      "webhooks or polling",
      "OCR or transcription jobs",
      "module SSOT writes",
      "mock fallback in formal mode",
    ],
    sourceWorkflow: {
      id: "DATTR-024A",
      status: "formal_read_contract_active",
      generatedAt,
      mode: "protected_read_empty_or_unavailable",
      bffBoundary: {
        loader: "Server Component loader",
        auth: "requireUser() before future persisted reads",
        authorization: "service-layer authorization before project/user-scoped source workflow access",
        mapper:
          "UI-safe DTO mapper; no Prisma models, provider payloads, secrets, cookies, or raw adapter data in Client Components",
        persistence: "no DB reads or writes in this slice",
      },
      summary: {
        totalObjects: sourceWorkflowModels.length,
        persistedObjects: 0,
        emptyOrUnavailableObjects: sourceWorkflowModels.length,
        hiddenMockFallback: false,
      },
      auditFamily: "ai-input.source-workflow",
      models: sourceWorkflowModels,
      prohibitedFallbacks: [
        "hidden mock connector rows",
        "hidden mock workflow rows",
        "fake persisted source records",
        "fake provider consent state",
        "fake proposal records",
        "module final writes",
      ],
      nextRunnableTask: "DATTR-024B",
    },
    sourceControlMatrix: {
      id: "AIINPUT-OPS-002",
      status: "formal_source_control_matrix_active",
      generatedAt,
      mode: "protected_read_no_connector_runtime",
      source: {
        acceptanceDoc: "docs/08_acceptance-and-qa/ACC-002_module-acceptance-criteria.md",
        splitContract: "docs/02_architecture-and-rules/ARC-031_ai-input-source-workflow-bff-split-contract.md",
        connectorBoundary: "src/lib/contracts/ai-input-source-workflow-connector-boundary.contract.ts",
        proposalActionContract: "src/lib/contracts/ai-input-source-workflow-proposal-action.contract.ts",
      },
      summary: {
        rowCount: sourceControlRows.length,
        connectedCount: sourceControlConnectedCount,
        plannedCount: sourceControlPlannedCount,
        needsSetupCount: sourceControlNeedsSetupCount,
        highRiskCount: sourceControlHighRiskCount,
        missingPermissionCount: sourceControlMissingPermissionCount,
        nextTask:
          "DATTR-024 remains blocked until proof target, migration, service authorization, RLS/audit storage, and connector runtime approvals exist.",
      },
      prohibitedRuntime: [
        "OAuth runtime",
        "webhook runtime",
        "polling runtime",
        "provider API calls",
        "file ingestion",
        "OCR or transcription",
        "raw adapter payload exposure",
        "Supabase reads or writes",
        "module final writes",
        "public output expansion",
        "external agent registration",
      ],
      rows: sourceControlRows,
    },
    sourceWorkflowGateMatrix: {
      id: "AIINPUT-OPS-003",
      status: "protected_source_workflow_gate_surface_active",
      generatedAt,
      mode: "protected_read_no_db_no_connector_runtime",
      sharedBy: ["ai-input", "admin", "settings"],
      source: {
        migrationDraft: "DATTR-024H-MIGRATION-DRAFT / prisma/migration-drafts/20260623_dattr_024h_source_workflow_create_only",
        proofRunner: "DATTR-024I-PROOF-RUNNER / scripts/ai-input-source-workflow-proof-runner.mjs",
        localProofBootstrap:
          "DATTR-024N-SOURCE-WORKFLOW-LOCAL-PROOF-BOOTSTRAP / scripts/ai-input-source-workflow-local-proof-bootstrap.mjs",
        serviceRuntime: "DATTR-024J-SERVICE-AUTHZ-RUNTIME / src/lib/services/ai-input-source-workflow.service.ts",
        rlsAuditStorage: "DATTR-024K-RLS-AUDIT-STORAGE / src/lib/contracts/ai-input-source-workflow-rls-audit-storage.contract.ts",
        connectorRuntimeApproval:
          "DATTR-024L-CONNECTOR-RUNTIME / src/lib/contracts/ai-input-source-workflow-connector-runtime-approval.contract.ts",
        acceptanceDoc: "docs/08_acceptance-and-qa/ACC-002_module-acceptance-criteria.md",
      },
      summary: {
        rowCount: sourceWorkflowGateRows.length,
        completeCount: sourceWorkflowGateRows.filter((row) => row.state === "complete").length,
        readyBoundaryCount: sourceWorkflowGateRows.filter((row) => row.state === "ready_boundary").length,
        dryRunOnlyCount: sourceWorkflowGateRows.filter((row) => row.state === "dry_run_only").length,
        humanApprovalRequiredCount: sourceWorkflowGateRows.filter((row) => row.state === "human_approval_required").length,
        blockedCount: sourceWorkflowGateRows.filter((row) => row.state === "blocked").length,
        nextTask:
          "Owner/operator can now follow DATTR-024Q proof target handoff; run AUTH-005 or WORK-009 when prerequisites appear.",
      },
      boundaryFlags: {
        databaseReadAllowed: false,
        databaseWriteAllowed: false,
        connectorRuntimeAllowed: false,
        oauthRuntimeAllowed: false,
        webhookRuntimeAllowed: false,
        pollingRuntimeAllowed: false,
        providerApiRuntimeAllowed: false,
        secretWriteAllowed: false,
        publicOutputAllowed: false,
        externalRegisterable: false,
      },
      prohibitedRuntime: [
        "schema/migration apply",
        "DB reads or writes",
        "OAuth callback runtime",
        "webhook runtime",
        "polling jobs",
        "provider API calls",
        "secret writes",
        "raw adapter payload exposure",
        "module final writes",
        "public output expansion",
        "external agent database access",
        "external registration",
      ],
      rows: sourceWorkflowGateRows,
    },
    sourceWorkflowProofBootstrap,
    rows: [
      {
        area: "AI cowork entry",
        status: "available",
        signal: "The conversation surface stays usable in formal mode.",
        safeExposure:
          "Only user-entered chat text and selected local UI state are handled by the Client Component in this slice.",
        nextGate: "Persist conversations or source context only after the formal data model is reviewed.",
        tone: "good",
      },
      {
        area: "SourceConnection read model",
        status: "not_persisted",
        signal: "No Supabase-backed SourceConnection loader is active for AI Input formal mode.",
        safeExposure:
          "Connector rows remain empty in formal mode instead of reusing mock LINE, Drive, Docs, RSS, Telegram, Gmail, or GitHub rows.",
        nextGate: "DATTR-024 must add service-layer authorization and UI-safe mappers before real connection rows appear.",
        tone: "blocked",
      },
      {
        area: "SourceAsset registry",
        status: "not_persisted",
        signal: "SourceAsset, RawSourceItem, snapshots, recognition, and normalized content are proposal-only.",
        safeExposure:
          "Formal mode exposes no raw payloads, provider IDs, external URLs, evidence excerpts, or file metadata from mock fixtures.",
        nextGate: "Review DATTR-017 migration A-D and DATTR-011 retention/encryption rules before storing assets.",
        tone: "blocked",
      },
      {
        area: "AIWorkflowRun and AIWorkItem",
        status: "not_persisted",
        signal: "No formal run, step, review item, or event-log BFF is active.",
        safeExposure:
          "AI 工作台 shows empty formal states and this readiness contract, not mock workflow rows.",
        nextGate: "Create read loaders for workflow runs and work items after schema and DB readiness are available.",
        tone: "blocked",
      },
      {
        area: "ModuleWriteIntent boundary",
        status: "blocked_by_design",
        signal: "AI Input formal outputs cannot write Work, Research, Client Portal, Finance, Life, or Company records.",
        safeExposure:
          "Future source-derived outputs must become reviewable ModuleWriteIntent proposals before module service commits.",
        nextGate: "Implement intent review with requireUser(), service authorization, and audit evidence in a later task.",
        tone: "warn",
      },
      {
        area: "Supabase public env",
        status: hasSupabasePublicConfig ? "configured" : "missing",
        signal: hasSupabasePublicConfig
          ? "Supabase public env is present for client/server auth surfaces."
          : "Supabase public URL/key are missing in this environment.",
        safeExposure:
          "The contract exposes only configured/missing state; it never renders URLs, keys, tokens, cookies, DB URLs, or provider payloads.",
        nextGate: "AUTH-005 and WORK-007 still require real session/Profile and reachable DB proof.",
        tone: hasSupabasePublicConfig ? "neutral" : "blocked",
      },
    ],
  }
}
